# ----------------------------------------------------------------------------
#
# Package             : scikit-image
# Source Repo         : https://github.com/scikit-image/scikit-image
# Travis Job Link     : https://travis-ci.com/github/asellappen/scikit-image/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python
dist: focal
arch:
  - amd64
  - ppc64le

python:
  - 3.7
  - 3.8

install:
  - pip install -r requirements.txt
  - pip install pytest
  - python setup.py install
  - pip install --no-deps -e .
script:
  - python -m pytest scikit-image/
  
