# ----------------------------------------------------------------------------
#
# Package             : scikit-image
# Source Repo         : https://github.com/scikit-image/scikit-image
# Travis Job Link     : https://travis-ci.com/github/asellappen/scikit-image/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language : python

arch:
    - amd64
    - ppc64le
    
python:
  - 3.8

install : 
  - set -ex
  - source tools/github/before_install.sh
  - set -ex
  - python setup.py sdist
  - if [[ $INSTALL_FROM_SDIST != "0" ]]; then
        pip uninstall cython -y;
        pip install dist/scikit-image-*.tar.gz;
    else
        pip install -vv -e .;
    fi
  - pip install  "--pre"  -r requirements/test.txt 
  - export MPL_DIR=`python -c 'import matplotlib; print(matplotlib.get_configdir())'`
  - mkdir -p ${MPL_DIR}
  - touch ${MPL_DIR}/matplotlibrc
  - source tools/github/script.sh
